### ISSUE TITLE
int .conf file: recovery_hdir, recovery_hs, recovery_vs, recovery_alt

### ISSUE THREAD

**Issue by fliescher** [nasa/daidalus#10]
I'm wondering about the usage of the recovery-flags in the .conf file and their usage inside DAIDALUS. It seems that those flags are only used for the daa.isEnabledRecoveryHorizontalDirectionBands() but not inside DAIDALUS itself?!

In my case I'd like to avoid intruders with the horizontal heading only, so I set recovery_hs, recovery_vs and recovery_alt each to false in my .conf file. Nevertheless when using daa.horizontalSpeedResolution() (and also vertical speed and altitude) it computes a guidance. 
So I need to check if horizontal speed Recovery is enabled by myself/in my own code. For me it would be handier to have the flags checked inside DAIDALUS already. What else would be the use of these flags? If I want to check them in my own code, I could just declare my own variables for it.
Are there any other reasons behind?

I'm using Release DAIDALUSv2.0.2c (C++)

**Comment by aarondutle** [comment]
The recovery flags only govern whether daidalus computes RECOVERY guidance for the indicated dimension. Recovery guidance can happen when there is no possible maneuver in the given dimension which will avoid the defined "corrective volume" in the coniguration file. If the recovery flag is set to true, when this happens, daidalus begins computing with a smaller (recovery) volume, and attempts to regain the standard well-clear volume. If this flag is set to false, then the bands will appear saturated (fully yellow and/or/red), indicating that there is no maneuver which will keep the aircraft in a well-clear status. I verified that this is working in our simulation (see attached image, where the left is computing recovery bands fro all dimensions, and the right is computing recovery only for horizontal direction).
![Screen Shot 2022-11-07 at 9 53 28 AM](https://user-images.githubusercontent.com/83716391/200340869-96c83797-60be-4c08-ae9b-cb4d197f5d9f.png)


It sounds like what you're attempting to do is to turn off the actual bands, or preferred guidance for a particular dimension. Since the bands and guidance are only computed when called, there is no built-in functionality for this. If you don't need the horizontal speed guidance, simply don't call the corresponding function.
